# Generated by Django 3.1.7 on 2021-09-08 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('course_id', models.BigAutoField(primary_key=True, serialize=False, verbose_name='课程ID')),
                ('course_name', models.CharField(max_length=30, verbose_name='课程名称')),
                ('grade', models.IntegerField(default=60, verbose_name='分数')),
            ],
        ),
        migrations.CreateModel(
            name='StudentInfo',
            fields=[
                ('stu_id', models.BigAutoField(primary_key=True, serialize=False, verbose_name='学生ID')),
                ('stu_name', models.CharField(max_length=30, verbose_name='学生姓名')),
                ('stu_phone', models.CharField(max_length=20, verbose_name='学生电话')),
                ('stu_addr', models.TextField(verbose_name='学生地址')),
                ('stu_faculty', models.CharField(max_length=20, verbose_name='院系')),
                ('stu_major', models.CharField(max_length=30, verbose_name='专业')),
            ],
        ),
        migrations.CreateModel(
            name='StudentPwd',
            fields=[
                ('stu_id', models.BigAutoField(primary_key=True, serialize=False, verbose_name='学生ID')),
                ('username', models.CharField(max_length=10, verbose_name='用户名')),
                ('password', models.CharField(max_length=10, verbose_name='密码')),
            ],
        ),
        migrations.DeleteModel(
            name='CourseModel',
        ),
    ]
