# Generated by Django 3.1.7 on 2021-09-12 07:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0002_auto_20210908_0914'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentinfo',
            name='stu_addr',
        ),
        migrations.RemoveField(
            model_name='studentinfo',
            name='stu_phone',
        ),
    ]
